### ISSUE TITLE
How to know it At work（how to use ?）

### ISSUE THREAD

**Issue by sunke5616** [akachronix/pubg-lagswitch#2]

**Comment by sunke5616** [comment]
g++: error:  src\lagg.cpp: No such file or directory
g++: error:  src\liblog\liblog.cpp: No such file or directory
g++: error:  src\lag_switch.cpp: No such file or directory
g++: fatal error: no input file

**Comment by sunke5616** [comment]
+ New-NetQosPolicy -Name CHANGEME2 -AppPathNameMatchCondition BeService ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (MSFT_NetQosPolicySettingData:ROOT/StandardCi...licySettingData) [New-
   NetQosPolicy], CimException
    + FullyQualifiedErrorId : MI RESULT 2,New-NetQosPolicy

**Comment by sunke5616** [comment]
Turning lagswitch on.
New-NetQosPolicy : 无法从客户端中访问 CIM 资源。
所在位置 行:1 字符: 1
+ New-NetQosPolicy -Name CHANGEME -AppPathNameMatchCondition TSLGame.ex ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (MSFT_NetQosPolicySettingData:ROOT/StandardCi...licySettingData) [New-
   NetQosPolicy], CimException
    + FullyQualifiedErrorId : MI RESULT 2,New-NetQosPolicy

**Comment by akachronix** [comment]
How about you git gud and immigrate to the US chinky chunk
